### ISSUE TITLE
Update front end

### ISSUE THREAD

**Issue by a-paxton** [thomasmorgan/joint-estimation-game#1]
# Done
- [x] Update to most recent version of Wallace
- [x] Resize and re-position line boxes
- [x] Create an interactive box (i.e., drawing box)
- [x] Get the stimulus box to disappear after 1 second
- [x] Get the response box to appear after 2 seconds
- [x] Randomize location of response box **[altered: shifted]**
- [x] Create a kind of listener that will stabilize the participant's choice
- [x] Disable multiple clicks during viewing of stimulus and response
- [x] Create submit/edit choices
- [x] Make boxes disappear when submit/edit choices are given
- [x] Send data to server when interim choices are selected
- [x] Get bar to reappear when participant selects "edit"
- [x] Figure out why `timed_out` response is sent 3 times (instead of just 1)
- [x] Figure out why `timed_out` response includes previous trial's number
- [x] Fetch partner's guess from server
- [x] Create shared training list
- [x] Create training corrections
- [x] Monitor for partner's choice when other partner chooses "submit" instead of "edit"
- [x] Fix questionnaire submission
- [x] Display partner's updated guess if both changed their guess

# To do

**Comment by thomasmorgan** [comment]
for showing/hiding see: http://api.jquery.com/toggle/

**Comment by thomasmorgan** [comment]
for positions see: https://api.jquery.com/position/

**Comment by a-paxton** [comment]
The front end should be completely ready to go. Closing issue.
